int _putchar(char c);
int print_alphabet();
int print_alphabet_x10();
int _islower(char alphabet);
int _isalpha(char alphabet);
int print_sign(char num);
int _abs(int);
int print_last_digit(int);
void times_table(void);
int add(int, int);
void print_to_98(int n);
